-- HR-25 timestamp-slug migration (generated by Nous, IMP-250).
-- Drizzle migrations are NOT Flyway-numeric.

-- Enum types (parity with schema.ts pgEnum — IMP-254)
CREATE TYPE account_status_enum AS ENUM ('active', 'archived');
CREATE TYPE account_type_enum AS ENUM ('group_bank', 'cash_box', 'treasurer_personal', 'external');
CREATE TYPE alert_audience_enum AS ENUM ('treasurer', 'platform_operator', 'both');
CREATE TYPE alert_severity_enum AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE audit_log_entry_actor_kind_enum AS ENUM ('member', 'platform_operator', 'system');
CREATE TYPE contribution_cycle_created_by_kind_enum AS ENUM ('system', 'member');
CREATE TYPE contribution_cycle_status_enum AS ENUM ('open', 'closed');
CREATE TYPE entity_version_change_kind_enum AS ENUM ('create', 'update', 'status_transition');
CREATE TYPE entity_version_created_by_kind_enum AS ENUM ('member', 'platform_operator', 'system');
CREATE TYPE expense_status_enum AS ENUM ('planned', 'paid');
CREATE TYPE extraordinary_collection_line_reconciliation_status_enum AS ENUM ('pending', 'regularized');
CREATE TYPE group_config_contribution_cycle_kind_enum AS ENUM ('monthly', 'weekly');
CREATE TYPE group_config_created_by_kind_enum AS ENUM ('platform_operator', 'member');
CREATE TYPE group_config_repayment_split_rule_enum AS ENUM ('interest_first', 'principal_first', 'even_split');
CREATE TYPE institution_kind_enum AS ENUM ('bank', 'coop', 'other');
CREATE TYPE institution_status_enum AS ENUM ('active', 'inactive');
CREATE TYPE loan_schedule_status_enum AS ENUM ('pendiente', 'parcial', 'pagado', 'atrasado', 'en_mora');
CREATE TYPE loan_status_enum AS ENUM ('proposed', 'originated', 'activo', 'pagado', 'cancelado', 'en_mora');
CREATE TYPE member_role_enum AS ENUM ('aportante', 'tesorera', 'presidente', 'secretaria');
CREATE TYPE member_status_enum AS ENUM ('activo', 'en_pausa', 'baja');
CREATE TYPE organization_status_enum AS ENUM ('active', 'paused', 'archived');
CREATE TYPE platform_operator_status_enum AS ENUM ('active', 'disabled');
CREATE TYPE reconciliation_cycle_resolution_kind_enum AS ENUM ('auto_within_tolerance', 'resolved_by_correction', 'annotated_acceptance');
CREATE TYPE slip_photo_attached_to_kind_enum AS ENUM ('contribution', 'repayment');
CREATE TYPE statement_archive_kind_enum AS ENUM ('monthly_close', 'monthly_member', 'year_end_member', 'year_end_share_out', 'year_end_snapshot', 'balance_banquito', 'year_end_economic_summary', 'monthly_summary');
CREATE TYPE surplus_governance_decision_status_enum AS ENUM ('draft', 'approved', 'locked');
CREATE TYPE user_account_status_enum AS ENUM ('active', 'disabled');
CREATE TYPE user_org_membership_status_enum AS ENUM ('active', 'revoked');
CREATE TYPE withdrawal_created_by_kind_enum AS ENUM ('member', 'system');
CREATE TYPE withdrawal_kind_enum AS ENUM ('member_refund', 'year_end_share_out', 'other');
CREATE TYPE year_end_share_out_status_enum AS ENUM ('draft', 'approved', 'distributed', 'locked');
CREATE TABLE IF NOT EXISTS alert (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID,
  alert_kind             TEXT NOT NULL,
  severity               alert_severity_enum NOT NULL,
  audience               alert_audience_enum NOT NULL,
  subject_kind           TEXT,
  subject_id             UUID,
  payload                JSONB NOT NULL,
  dedup_window_end       TIMESTAMPTZ NOT NULL,
  dismissed_at           TIMESTAMPTZ,
  dismissed_by           UUID,
  snoozed_until          TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_alert_org_id_alert_kind_subject_kind_subject_id_dedup_window_end UNIQUE (org_id, alert_kind, subject_kind, subject_id, dedup_window_end)
);
CREATE INDEX IF NOT EXISTS idx_alert_org_id ON alert(org_id);

CREATE TABLE IF NOT EXISTS audit_log_entry (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID,
  actor_kind             audit_log_entry_actor_kind_enum NOT NULL,
  actor_id               UUID NOT NULL,
  action_kind            TEXT NOT NULL,
  subject_kind           TEXT NOT NULL,
  subject_id             UUID,
  payload_snapshot       JSONB NOT NULL,
  reason                 TEXT,
  at                     TIMESTAMPTZ NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_log_entry_org_id ON audit_log_entry(org_id);

CREATE TABLE IF NOT EXISTS entity_version (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID,
  entity_kind            TEXT NOT NULL,
  entity_id              UUID NOT NULL,
  version                INTEGER NOT NULL,
  valid_from             TIMESTAMPTZ NOT NULL,
  valid_to               TIMESTAMPTZ,
  payload_snapshot       JSONB NOT NULL,
  change_kind            entity_version_change_kind_enum NOT NULL,
  change_reason          TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        entity_version_created_by_kind_enum NOT NULL,
  CONSTRAINT uq_entity_version_entity_kind_entity_id_version UNIQUE (entity_kind, entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_entity_version_org_id ON entity_version(org_id);

CREATE TABLE IF NOT EXISTS interest_accrual (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  loan_id                UUID NOT NULL,
  accrued_on             DATE NOT NULL,
  principal_basis        NUMERIC(18, 4) NOT NULL,
  period_days            INTEGER NOT NULL,
  rate_value             NUMERIC(8, 4) NOT NULL,
  interest_amount        NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  recorded_at            TIMESTAMPTZ NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_interest_accrual_loan_id_accrued_on UNIQUE (loan_id, accrued_on)
);
CREATE INDEX IF NOT EXISTS idx_interest_accrual_org_id ON interest_accrual(org_id);
CREATE INDEX IF NOT EXISTS idx_interest_accrual_loan_id ON interest_accrual(loan_id);

CREATE TABLE IF NOT EXISTS member (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  display_name           TEXT NOT NULL,
  whatsapp_number        TEXT,
  joined_on              DATE NOT NULL,
  role                   member_role_enum NOT NULL,
  status                 member_status_enum NOT NULL,
  auth_subject           TEXT,
  initial_savings_balance NUMERIC(18, 4) NOT NULL,
  notes                  TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID
);
CREATE INDEX IF NOT EXISTS idx_member_org_id ON member(org_id);

CREATE TABLE IF NOT EXISTS contribution_cycle (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  cycle_label            TEXT NOT NULL,
  kind                   TEXT NOT NULL,
  opens_on               DATE NOT NULL,
  closes_on              DATE NOT NULL,
  expected_amount_per_member NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  status                 contribution_cycle_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        contribution_cycle_created_by_kind_enum NOT NULL,
  CONSTRAINT uq_contribution_cycle_org_id_cycle_label UNIQUE (org_id, cycle_label)
);
CREATE INDEX IF NOT EXISTS idx_contribution_cycle_org_id ON contribution_cycle(org_id);

CREATE TABLE IF NOT EXISTS contribution (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  cycle_id               UUID NOT NULL,
  member_id              UUID NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  dated_on               DATE NOT NULL,
  recorded_at            TIMESTAMPTZ NOT NULL,
  slip_photo_id          UUID,
  notes                  TEXT,
  reverses_id            UUID,
  reverse_reason         TEXT,
  client_request_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_contribution_org_id_client_request_id UNIQUE (org_id, client_request_id)
);
CREATE INDEX IF NOT EXISTS idx_contribution_org_id ON contribution(org_id);
CREATE INDEX IF NOT EXISTS idx_contribution_cycle_id ON contribution(cycle_id);
CREATE INDEX IF NOT EXISTS idx_contribution_member_id ON contribution(member_id);
CREATE INDEX IF NOT EXISTS idx_contribution_slip_photo_id ON contribution(slip_photo_id);
CREATE INDEX IF NOT EXISTS idx_contribution_reverses_id ON contribution(reverses_id);

CREATE TABLE IF NOT EXISTS withdrawal (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  member_id              UUID NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  dated_on               DATE NOT NULL,
  recorded_at            TIMESTAMPTZ NOT NULL,
  kind                   withdrawal_kind_enum NOT NULL,
  share_out_id           UUID,
  notes                  TEXT,
  reverses_id            UUID,
  reverse_reason         TEXT,
  client_request_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        withdrawal_created_by_kind_enum NOT NULL,
  year_end_share_out_line_id UUID,
  CONSTRAINT uq_withdrawal_org_id_client_request_id UNIQUE (org_id, client_request_id)
);
CREATE INDEX IF NOT EXISTS idx_withdrawal_org_id ON withdrawal(org_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_year_end_share_out_line_id ON withdrawal(year_end_share_out_line_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_member_id ON withdrawal(member_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_share_out_id ON withdrawal(share_out_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_reverses_id ON withdrawal(reverses_id);

CREATE TABLE IF NOT EXISTS expense (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  purpose                TEXT NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  beneficiary_member_id  UUID,
  beneficiary_text       TEXT,
  incurred_on            DATE NOT NULL,
  status                 expense_status_enum NOT NULL,
  recorded_at            TIMESTAMPTZ NOT NULL,
  reverses_id            UUID,
  reverse_reason         TEXT,
  client_request_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_expense_org_id_client_request_id UNIQUE (org_id, client_request_id)
);
CREATE INDEX IF NOT EXISTS idx_expense_org_id ON expense(org_id);
CREATE INDEX IF NOT EXISTS idx_expense_beneficiary_member_id ON expense(beneficiary_member_id);
CREATE INDEX IF NOT EXISTS idx_expense_reverses_id ON expense(reverses_id);

CREATE TABLE IF NOT EXISTS slip_photo (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  uri                    TEXT NOT NULL,
  mime_type              TEXT NOT NULL,
  byte_size              INTEGER NOT NULL,
  attached_to_kind       slip_photo_attached_to_kind_enum NOT NULL,
  attached_to_id         UUID NOT NULL,
  uploaded_at            TIMESTAMPTZ NOT NULL,
  uploaded_by            UUID NOT NULL,
  uploaded_by_kind       TEXT NOT NULL,
  contribution_id        UUID,
  repayment_id           UUID
);
CREATE INDEX IF NOT EXISTS idx_slip_photo_org_id ON slip_photo(org_id);
CREATE INDEX IF NOT EXISTS idx_slip_photo_contribution_id ON slip_photo(contribution_id);
CREATE INDEX IF NOT EXISTS idx_slip_photo_repayment_id ON slip_photo(repayment_id);

CREATE TABLE IF NOT EXISTS account (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  name                   TEXT NOT NULL,
  type                   account_type_enum NOT NULL,
  is_group_fund          BOOLEAN NOT NULL,
  last4                  TEXT,
  product_type           TEXT,
  institution_id         UUID,
  status                 account_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_account_org_id ON account(org_id);
CREATE INDEX IF NOT EXISTS idx_account_institution_id ON account(institution_id);

CREATE TABLE IF NOT EXISTS transfer (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  from_account_id        UUID NOT NULL,
  to_account_id          UUID NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  dated_on               DATE NOT NULL,
  purpose                TEXT,
  regularizes_kind       TEXT,
  regularizes_id         UUID,
  slip_photo_id          UUID,
  reverses_id            UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transfer_org_id ON transfer(org_id);
CREATE INDEX IF NOT EXISTS idx_transfer_from_account_id ON transfer(from_account_id);
CREATE INDEX IF NOT EXISTS idx_transfer_to_account_id ON transfer(to_account_id);
CREATE INDEX IF NOT EXISTS idx_transfer_slip_photo_id ON transfer(slip_photo_id);
CREATE INDEX IF NOT EXISTS idx_transfer_reverses_id ON transfer(reverses_id);

CREATE TABLE IF NOT EXISTS extraordinary_collection (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  kind                   TEXT NOT NULL,
  purpose                TEXT NOT NULL,
  beneficiary_member_id  UUID,
  target_amount          NUMERIC(18, 4),
  status                 TEXT NOT NULL,
  opened_on              DATE NOT NULL,
  paid_out_expense_id    UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_org_id ON extraordinary_collection(org_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_beneficiary_member_id ON extraordinary_collection(beneficiary_member_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_paid_out_expense_id ON extraordinary_collection(paid_out_expense_id);

CREATE TABLE IF NOT EXISTS extraordinary_collection_line (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  collection_id          UUID NOT NULL,
  member_id              UUID NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  account_id             UUID,
  reconciliation_status  extraordinary_collection_line_reconciliation_status_enum NOT NULL,
  dated_on               DATE NOT NULL,
  slip_photo_id          UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_line_org_id ON extraordinary_collection_line(org_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_line_collection_id ON extraordinary_collection_line(collection_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_line_member_id ON extraordinary_collection_line(member_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_line_account_id ON extraordinary_collection_line(account_id);
CREATE INDEX IF NOT EXISTS idx_extraordinary_collection_line_slip_photo_id ON extraordinary_collection_line(slip_photo_id);

CREATE TABLE IF NOT EXISTS loan (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  member_id              UUID NOT NULL,
  principal_amount       NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  rate_value             NUMERIC(8, 4) NOT NULL,
  rate_model             TEXT NOT NULL,
  term_periods           INTEGER NOT NULL,
  grace_periods          INTEGER NOT NULL,
  originated_on          DATE NOT NULL,
  status                 loan_status_enum NOT NULL,
  purpose                TEXT,
  client_request_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID,
  CONSTRAINT uq_loan_org_id_client_request_id UNIQUE (org_id, client_request_id)
);
CREATE INDEX IF NOT EXISTS idx_loan_org_id ON loan(org_id);
CREATE INDEX IF NOT EXISTS idx_loan_member_id ON loan(member_id);

CREATE TABLE IF NOT EXISTS loan_schedule (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  loan_id                UUID NOT NULL,
  period_index           INTEGER NOT NULL,
  due_on                 DATE NOT NULL,
  principal_due          NUMERIC(18, 4) NOT NULL,
  interest_due           NUMERIC(18, 4) NOT NULL,
  status                 loan_schedule_status_enum NOT NULL,
  paid_principal_to_date NUMERIC(18, 4) NOT NULL,
  paid_interest_to_date  NUMERIC(18, 4) NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_loan_schedule_loan_id_period_index UNIQUE (loan_id, period_index)
);
CREATE INDEX IF NOT EXISTS idx_loan_schedule_org_id ON loan_schedule(org_id);
CREATE INDEX IF NOT EXISTS idx_loan_schedule_loan_id ON loan_schedule(loan_id);

CREATE TABLE IF NOT EXISTS loan_fee (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  loan_id                UUID NOT NULL,
  loan_schedule_id       UUID,
  fee_kind               TEXT NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  dated_on               DATE NOT NULL,
  accrued_on             DATE NOT NULL,
  group_config_version   INTEGER NOT NULL,
  feeds_surplus          BOOLEAN NOT NULL,
  account_id             UUID,
  reconciliation_status  TEXT,
  reverses_id            UUID,
  reverse_reason         TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_loan_fee_loan_id_fee_kind_accrued_on UNIQUE (loan_id, fee_kind, accrued_on)
);
CREATE INDEX IF NOT EXISTS idx_loan_fee_org_id ON loan_fee(org_id);
CREATE INDEX IF NOT EXISTS idx_loan_fee_loan_id ON loan_fee(loan_id);
CREATE INDEX IF NOT EXISTS idx_loan_fee_loan_schedule_id ON loan_fee(loan_schedule_id);
CREATE INDEX IF NOT EXISTS idx_loan_fee_account_id ON loan_fee(account_id);
CREATE INDEX IF NOT EXISTS idx_loan_fee_reverses_id ON loan_fee(reverses_id);

CREATE TABLE IF NOT EXISTS repayment (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  loan_id                UUID NOT NULL,
  member_id              UUID NOT NULL,
  amount                 NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  applied_to_principal   NUMERIC(18, 4) NOT NULL,
  applied_to_interest    NUMERIC(18, 4) NOT NULL,
  dated_on               DATE NOT NULL,
  recorded_at            TIMESTAMPTZ NOT NULL,
  slip_photo_id          UUID,
  notes                  TEXT,
  reverses_id            UUID,
  reverse_reason         TEXT,
  client_request_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_repayment_org_id_client_request_id UNIQUE (org_id, client_request_id)
);
CREATE INDEX IF NOT EXISTS idx_repayment_org_id ON repayment(org_id);
CREATE INDEX IF NOT EXISTS idx_repayment_loan_id ON repayment(loan_id);
CREATE INDEX IF NOT EXISTS idx_repayment_member_id ON repayment(member_id);
CREATE INDEX IF NOT EXISTS idx_repayment_slip_photo_id ON repayment(slip_photo_id);
CREATE INDEX IF NOT EXISTS idx_repayment_reverses_id ON repayment(reverses_id);

CREATE TABLE IF NOT EXISTS organization (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  display_name           TEXT NOT NULL,
  country_code           TEXT NOT NULL,
  currency_code          TEXT NOT NULL,
  timezone               TEXT NOT NULL,
  default_language       TEXT NOT NULL,
  status                 organization_status_enum NOT NULL,
  branding_logo_uri      TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID,
  platform_operator_id   UUID
);
CREATE INDEX IF NOT EXISTS idx_organization_platform_operator_id ON organization(platform_operator_id);

CREATE TABLE IF NOT EXISTS group_config (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  version                INTEGER NOT NULL,
  valid_from             TIMESTAMPTZ NOT NULL,
  valid_to               TIMESTAMPTZ,
  contribution_cycle_kind group_config_contribution_cycle_kind_enum NOT NULL,
  contribution_amount    NUMERIC(18, 4) NOT NULL,
  currency_code          TEXT NOT NULL,
  loan_rate_model        TEXT NOT NULL,
  loan_rate_value        NUMERIC(8, 4) NOT NULL,
  loan_grace_periods     INTEGER NOT NULL,
  loan_to_savings_cap_ratio NUMERIC(4, 2) NOT NULL,
  interest_resolution    TEXT NOT NULL,
  repayment_split_rule   group_config_repayment_split_rule_enum NOT NULL,
  pays_savings_interest  BOOLEAN NOT NULL,
  savings_interest_rate  NUMERIC(8, 4),
  year_end_share_out_formula TEXT,
  safety_margin_amount   NUMERIC(18, 4) NOT NULL,
  reconciliation_tolerance_amount NUMERIC(18, 4) NOT NULL,
  late_threshold_days    INTEGER NOT NULL,
  mora_threshold_days    INTEGER NOT NULL,
  config                 JSONB NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        group_config_created_by_kind_enum NOT NULL,
  CONSTRAINT uq_group_config_org_id_version UNIQUE (org_id, version)
);
CREATE INDEX IF NOT EXISTS idx_group_config_org_id ON group_config(org_id);

CREATE TABLE IF NOT EXISTS platform_operator (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  display_name           TEXT NOT NULL,
  email                  TEXT NOT NULL,
  auth_subject           TEXT,
  status                 platform_operator_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  updated_at             TIMESTAMPTZ,
  CONSTRAINT uq_platform_operator_email UNIQUE (email),
  CONSTRAINT uq_platform_operator_auth_subject UNIQUE (auth_subject)
);

CREATE TABLE IF NOT EXISTS impersonation (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  platform_operator_id   UUID NOT NULL,
  started_at             TIMESTAMPTZ NOT NULL,
  ended_at               TIMESTAMPTZ,
  reason                 TEXT NOT NULL,
  mode                   TEXT NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_impersonation_org_id ON impersonation(org_id);
CREATE INDEX IF NOT EXISTS idx_impersonation_platform_operator_id ON impersonation(platform_operator_id);

CREATE TABLE IF NOT EXISTS user_account (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  auth_subject           TEXT NOT NULL,
  email                  TEXT NOT NULL,
  display_name           TEXT NOT NULL,
  status                 user_account_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  updated_at             TIMESTAMPTZ,
  CONSTRAINT uq_user_account_auth_subject UNIQUE (auth_subject),
  CONSTRAINT uq_user_account_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_org_membership (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  user_id                UUID NOT NULL,
  org_id                 UUID NOT NULL,
  role                   TEXT NOT NULL,
  status                 user_org_membership_status_enum NOT NULL,
  member_id              UUID,
  granted_at             TIMESTAMPTZ NOT NULL,
  revoked_at             TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_user_org_membership_org_id ON user_org_membership(org_id);
CREATE INDEX IF NOT EXISTS idx_user_org_membership_user_id ON user_org_membership(user_id);
CREATE INDEX IF NOT EXISTS idx_user_org_membership_member_id ON user_org_membership(member_id);

CREATE TABLE IF NOT EXISTS country (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  iso2                   TEXT NOT NULL,
  iso3                   TEXT NOT NULL,
  name                   TEXT NOT NULL,
  currency_code          TEXT NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_country_iso2 UNIQUE (iso2)
);

CREATE TABLE IF NOT EXISTS institution (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  country_id             UUID NOT NULL,
  name                   TEXT NOT NULL,
  kind                   institution_kind_enum NOT NULL,
  swift_bic              TEXT,
  status                 institution_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_institution_country_id ON institution(country_id);

CREATE TABLE IF NOT EXISTS reconciliation_cycle (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  cycle_id               UUID NOT NULL,
  declared_bank_balance  NUMERIC(18, 4) NOT NULL,
  computed_pool_balance  NUMERIC(18, 4) NOT NULL,
  discrepancy_amount     NUMERIC(18, 4) NOT NULL,
  tolerance_amount       NUMERIC(18, 4) NOT NULL,
  resolution_kind        reconciliation_cycle_resolution_kind_enum NOT NULL,
  resolution_note        TEXT,
  closed_at              TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_reconciliation_cycle_org_id_cycle_id UNIQUE (org_id, cycle_id)
);
CREATE INDEX IF NOT EXISTS idx_reconciliation_cycle_org_id ON reconciliation_cycle(org_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_cycle_cycle_id ON reconciliation_cycle(cycle_id);

CREATE TABLE IF NOT EXISTS period_close (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  cycle_id               UUID NOT NULL,
  reconciliation_cycle_id UUID NOT NULL,
  closed_at              TIMESTAMPTZ NOT NULL,
  closed_by              UUID NOT NULL,
  closed_by_kind         TEXT NOT NULL,
  is_year_end            BOOLEAN NOT NULL,
  monthly_close_statement_id UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_period_close_org_id_cycle_id UNIQUE (org_id, cycle_id)
);
CREATE INDEX IF NOT EXISTS idx_period_close_org_id ON period_close(org_id);
CREATE INDEX IF NOT EXISTS idx_period_close_cycle_id ON period_close(cycle_id);
CREATE INDEX IF NOT EXISTS idx_period_close_reconciliation_cycle_id ON period_close(reconciliation_cycle_id);
CREATE INDEX IF NOT EXISTS idx_period_close_monthly_close_statement_id ON period_close(monthly_close_statement_id);

CREATE TABLE IF NOT EXISTS statement_archive (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  kind                   statement_archive_kind_enum NOT NULL,
  member_id              UUID,
  period_label           TEXT NOT NULL,
  pdf_uri                TEXT NOT NULL,
  canonical_payload_hash TEXT NOT NULL,
  generated_at           TIMESTAMPTZ NOT NULL,
  period_close_id        UUID,
  year_end_share_out_id  UUID,
  byte_size              INTEGER NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_statement_archive_org_id_kind_member_id_period_label UNIQUE (org_id, kind, member_id, period_label)
);
CREATE INDEX IF NOT EXISTS idx_statement_archive_org_id ON statement_archive(org_id);
CREATE INDEX IF NOT EXISTS idx_statement_archive_member_id ON statement_archive(member_id);
CREATE INDEX IF NOT EXISTS idx_statement_archive_period_close_id ON statement_archive(period_close_id);
CREATE INDEX IF NOT EXISTS idx_statement_archive_year_end_share_out_id ON statement_archive(year_end_share_out_id);

CREATE TABLE IF NOT EXISTS surplus_governance_decision (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  year                   INTEGER NOT NULL,
  version                INTEGER NOT NULL,
  valid_from             TIMESTAMPTZ NOT NULL,
  valid_to               TIMESTAMPTZ,
  distributable_surplus  NUMERIC(18, 4) NOT NULL,
  reparto_total          NUMERIC(18, 4) NOT NULL,
  reserva_amount         NUMERIC(18, 4) NOT NULL,
  reserva_disposition    TEXT NOT NULL,
  loan_pool_pct          NUMERIC(6, 4) NOT NULL,
  savings_pool_pct       NUMERIC(6, 4) NOT NULL,
  status                 surplus_governance_decision_status_enum NOT NULL,
  decided_at             TIMESTAMPTZ,
  decided_by             UUID NOT NULL,
  decided_by_kind        TEXT NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_surplus_governance_decision_org_id_year_version UNIQUE (org_id, year, version)
);
CREATE INDEX IF NOT EXISTS idx_surplus_governance_decision_org_id ON surplus_governance_decision(org_id);

CREATE TABLE IF NOT EXISTS year_end_share_out (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  year                   INTEGER NOT NULL,
  period_close_id        UUID NOT NULL,
  formula_at_run         TEXT,
  total_pool_at_run      NUMERIC(18, 4) NOT NULL,
  total_commitment       NUMERIC(18, 4) NOT NULL,
  total_approved         NUMERIC(18, 4),
  surplus_or_shortfall_at_approval NUMERIC(18, 4),
  governance_decision_id UUID,
  distributable_surplus  NUMERIC(18, 4),
  cxc_anterior           NUMERIC(18, 4),
  reparto_total          NUMERIC(18, 4),
  loan_pool_amount       NUMERIC(18, 4),
  savings_pool_amount    NUMERIC(18, 4),
  alicuota_prestamos     NUMERIC(12, 10),
  alicuota_ahorros       NUMERIC(12, 10),
  ajuste_amount          NUMERIC(18, 4),
  status                 year_end_share_out_status_enum NOT NULL,
  approved_at            TIMESTAMPTZ,
  approved_by            UUID,
  approved_by_kind       TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_year_end_share_out_org_id_year UNIQUE (org_id, year)
);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_org_id ON year_end_share_out(org_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_period_close_id ON year_end_share_out(period_close_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_governance_decision_id ON year_end_share_out(governance_decision_id);

CREATE TABLE IF NOT EXISTS year_end_share_out_line (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  year_end_share_out_id  UUID NOT NULL,
  member_id              UUID NOT NULL,
  accumulated_savings_at_run NUMERIC(18, 4) NOT NULL,
  loan_activity_basis    NUMERIC(18, 4),
  loan_bonus_c           NUMERIC(18, 4),
  savings_interest       NUMERIC(18, 4),
  draft_share_amount     NUMERIC(18, 4) NOT NULL,
  override_share_amount  NUMERIC(18, 4),
  override_reason        TEXT,
  final_share_amount     NUMERIC(18, 4) NOT NULL,
  disposition            TEXT,
  disposition_motive     TEXT,
  withdrawal_id          UUID,
  retained_contribution_id UUID,
  member_statement_id    UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_year_end_share_out_line_year_end_share_out_id_member_id UNIQUE (year_end_share_out_id, member_id)
);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_org_id ON year_end_share_out_line(org_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_year_end_share_out_id ON year_end_share_out_line(year_end_share_out_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_member_id ON year_end_share_out_line(member_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_withdrawal_id ON year_end_share_out_line(withdrawal_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_retained_contribution_id ON year_end_share_out_line(retained_contribution_id);
CREATE INDEX IF NOT EXISTS idx_year_end_share_out_line_member_statement_id ON year_end_share_out_line(member_statement_id);

CREATE TABLE IF NOT EXISTS year_end_balance_snapshot (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  year                   INTEGER NOT NULL,
  snapshot_date          DATE NOT NULL,
  period_close_id        UUID NOT NULL,
  prior_snapshot_id      UUID,
  total_ahorros          NUMERIC(18, 4) NOT NULL,
  total_cuota_acumulada  NUMERIC(18, 4) NOT NULL,
  total_prestamos_por_cobrar NUMERIC(18, 4) NOT NULL,
  total_interes_por_cobrar NUMERIC(18, 4) NOT NULL,
  banco_balance          NUMERIC(18, 4) NOT NULL,
  cxc_anterior           NUMERIC(18, 4) NOT NULL,
  group_config_version   INTEGER NOT NULL,
  canonical_payload_hash TEXT NOT NULL,
  statement_archive_id   UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by_kind        TEXT NOT NULL,
  CONSTRAINT uq_year_end_balance_snapshot_org_id_year UNIQUE (org_id, year)
);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_org_id ON year_end_balance_snapshot(org_id);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_period_close_id ON year_end_balance_snapshot(period_close_id);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_prior_snapshot_id ON year_end_balance_snapshot(prior_snapshot_id);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_statement_archive_id ON year_end_balance_snapshot(statement_archive_id);

CREATE TABLE IF NOT EXISTS year_end_balance_snapshot_line (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  org_id                 UUID NOT NULL,
  snapshot_id            UUID NOT NULL,
  member_id              UUID NOT NULL,
  ahorros_balance        NUMERIC(18, 4) NOT NULL,
  cuota_acumulada        NUMERIC(18, 4) NOT NULL,
  prestamos_por_cobrar   NUMERIC(18, 4) NOT NULL,
  interes_por_cobrar     NUMERIC(18, 4) NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_year_end_balance_snapshot_line_snapshot_id_member_id UNIQUE (snapshot_id, member_id)
);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_line_org_id ON year_end_balance_snapshot_line(org_id);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_line_snapshot_id ON year_end_balance_snapshot_line(snapshot_id);
CREATE INDEX IF NOT EXISTS idx_year_end_balance_snapshot_line_member_id ON year_end_balance_snapshot_line(member_id);

-- Foreign keys (deferred ALTER pass — added after all tables exist,
-- so forward-references, cycles, and self-refs all apply cleanly)
ALTER TABLE interest_accrual ADD CONSTRAINT fk_interest_accrual_loan_id FOREIGN KEY (loan_id) REFERENCES loan(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_cycle_id FOREIGN KEY (cycle_id) REFERENCES contribution_cycle(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_slip_photo_id FOREIGN KEY (slip_photo_id) REFERENCES slip_photo(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_reverses_id FOREIGN KEY (reverses_id) REFERENCES contribution(id);
ALTER TABLE withdrawal ADD CONSTRAINT fk_withdrawal_year_end_share_out_line_id FOREIGN KEY (year_end_share_out_line_id) REFERENCES year_end_share_out_line(id);
ALTER TABLE withdrawal ADD CONSTRAINT fk_withdrawal_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE withdrawal ADD CONSTRAINT fk_withdrawal_share_out_id FOREIGN KEY (share_out_id) REFERENCES year_end_share_out(id);
ALTER TABLE withdrawal ADD CONSTRAINT fk_withdrawal_reverses_id FOREIGN KEY (reverses_id) REFERENCES withdrawal(id);
ALTER TABLE expense ADD CONSTRAINT fk_expense_beneficiary_member_id FOREIGN KEY (beneficiary_member_id) REFERENCES member(id);
ALTER TABLE expense ADD CONSTRAINT fk_expense_reverses_id FOREIGN KEY (reverses_id) REFERENCES expense(id);
ALTER TABLE slip_photo ADD CONSTRAINT fk_slip_photo_contribution_id FOREIGN KEY (contribution_id) REFERENCES contribution(id);
ALTER TABLE slip_photo ADD CONSTRAINT fk_slip_photo_repayment_id FOREIGN KEY (repayment_id) REFERENCES repayment(id);
ALTER TABLE account ADD CONSTRAINT fk_account_institution_id FOREIGN KEY (institution_id) REFERENCES institution(id);
ALTER TABLE transfer ADD CONSTRAINT fk_transfer_from_account_id FOREIGN KEY (from_account_id) REFERENCES account(id);
ALTER TABLE transfer ADD CONSTRAINT fk_transfer_to_account_id FOREIGN KEY (to_account_id) REFERENCES account(id);
ALTER TABLE transfer ADD CONSTRAINT fk_transfer_slip_photo_id FOREIGN KEY (slip_photo_id) REFERENCES slip_photo(id);
ALTER TABLE transfer ADD CONSTRAINT fk_transfer_reverses_id FOREIGN KEY (reverses_id) REFERENCES transfer(id);
ALTER TABLE extraordinary_collection ADD CONSTRAINT fk_extraordinary_collection_beneficiary_member_id FOREIGN KEY (beneficiary_member_id) REFERENCES member(id);
ALTER TABLE extraordinary_collection ADD CONSTRAINT fk_extraordinary_collection_paid_out_expense_id FOREIGN KEY (paid_out_expense_id) REFERENCES expense(id);
ALTER TABLE extraordinary_collection_line ADD CONSTRAINT fk_extraordinary_collection_line_collection_id FOREIGN KEY (collection_id) REFERENCES extraordinary_collection(id);
ALTER TABLE extraordinary_collection_line ADD CONSTRAINT fk_extraordinary_collection_line_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE extraordinary_collection_line ADD CONSTRAINT fk_extraordinary_collection_line_account_id FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE extraordinary_collection_line ADD CONSTRAINT fk_extraordinary_collection_line_slip_photo_id FOREIGN KEY (slip_photo_id) REFERENCES slip_photo(id);
ALTER TABLE loan ADD CONSTRAINT fk_loan_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE loan_schedule ADD CONSTRAINT fk_loan_schedule_loan_id FOREIGN KEY (loan_id) REFERENCES loan(id);
ALTER TABLE loan_fee ADD CONSTRAINT fk_loan_fee_loan_id FOREIGN KEY (loan_id) REFERENCES loan(id);
ALTER TABLE loan_fee ADD CONSTRAINT fk_loan_fee_loan_schedule_id FOREIGN KEY (loan_schedule_id) REFERENCES loan_schedule(id);
ALTER TABLE loan_fee ADD CONSTRAINT fk_loan_fee_account_id FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE loan_fee ADD CONSTRAINT fk_loan_fee_reverses_id FOREIGN KEY (reverses_id) REFERENCES loan_fee(id);
ALTER TABLE repayment ADD CONSTRAINT fk_repayment_loan_id FOREIGN KEY (loan_id) REFERENCES loan(id);
ALTER TABLE repayment ADD CONSTRAINT fk_repayment_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE repayment ADD CONSTRAINT fk_repayment_slip_photo_id FOREIGN KEY (slip_photo_id) REFERENCES slip_photo(id);
ALTER TABLE repayment ADD CONSTRAINT fk_repayment_reverses_id FOREIGN KEY (reverses_id) REFERENCES repayment(id);
ALTER TABLE organization ADD CONSTRAINT fk_organization_platform_operator_id FOREIGN KEY (platform_operator_id) REFERENCES platform_operator(id);
ALTER TABLE impersonation ADD CONSTRAINT fk_impersonation_platform_operator_id FOREIGN KEY (platform_operator_id) REFERENCES platform_operator(id);
ALTER TABLE user_org_membership ADD CONSTRAINT fk_user_org_membership_user_id FOREIGN KEY (user_id) REFERENCES user_account(id);
ALTER TABLE user_org_membership ADD CONSTRAINT fk_user_org_membership_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE institution ADD CONSTRAINT fk_institution_country_id FOREIGN KEY (country_id) REFERENCES country(id);
ALTER TABLE reconciliation_cycle ADD CONSTRAINT fk_reconciliation_cycle_cycle_id FOREIGN KEY (cycle_id) REFERENCES contribution_cycle(id);
ALTER TABLE period_close ADD CONSTRAINT fk_period_close_cycle_id FOREIGN KEY (cycle_id) REFERENCES contribution_cycle(id);
ALTER TABLE period_close ADD CONSTRAINT fk_period_close_reconciliation_cycle_id FOREIGN KEY (reconciliation_cycle_id) REFERENCES reconciliation_cycle(id);
ALTER TABLE period_close ADD CONSTRAINT fk_period_close_monthly_close_statement_id FOREIGN KEY (monthly_close_statement_id) REFERENCES statement_archive(id);
ALTER TABLE statement_archive ADD CONSTRAINT fk_statement_archive_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE statement_archive ADD CONSTRAINT fk_statement_archive_period_close_id FOREIGN KEY (period_close_id) REFERENCES period_close(id);
ALTER TABLE statement_archive ADD CONSTRAINT fk_statement_archive_year_end_share_out_id FOREIGN KEY (year_end_share_out_id) REFERENCES year_end_share_out(id);
ALTER TABLE year_end_share_out ADD CONSTRAINT fk_year_end_share_out_period_close_id FOREIGN KEY (period_close_id) REFERENCES period_close(id);
ALTER TABLE year_end_share_out ADD CONSTRAINT fk_year_end_share_out_governance_decision_id FOREIGN KEY (governance_decision_id) REFERENCES surplus_governance_decision(id);
ALTER TABLE year_end_share_out_line ADD CONSTRAINT fk_year_end_share_out_line_year_end_share_out_id FOREIGN KEY (year_end_share_out_id) REFERENCES year_end_share_out(id);
ALTER TABLE year_end_share_out_line ADD CONSTRAINT fk_year_end_share_out_line_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE year_end_share_out_line ADD CONSTRAINT fk_year_end_share_out_line_withdrawal_id FOREIGN KEY (withdrawal_id) REFERENCES withdrawal(id);
ALTER TABLE year_end_share_out_line ADD CONSTRAINT fk_year_end_share_out_line_retained_contribution_id FOREIGN KEY (retained_contribution_id) REFERENCES contribution(id);
ALTER TABLE year_end_share_out_line ADD CONSTRAINT fk_year_end_share_out_line_member_statement_id FOREIGN KEY (member_statement_id) REFERENCES statement_archive(id);
ALTER TABLE year_end_balance_snapshot ADD CONSTRAINT fk_year_end_balance_snapshot_period_close_id FOREIGN KEY (period_close_id) REFERENCES period_close(id);
ALTER TABLE year_end_balance_snapshot ADD CONSTRAINT fk_year_end_balance_snapshot_prior_snapshot_id FOREIGN KEY (prior_snapshot_id) REFERENCES year_end_balance_snapshot(id);
ALTER TABLE year_end_balance_snapshot ADD CONSTRAINT fk_year_end_balance_snapshot_statement_archive_id FOREIGN KEY (statement_archive_id) REFERENCES statement_archive(id);
ALTER TABLE year_end_balance_snapshot_line ADD CONSTRAINT fk_year_end_balance_snapshot_line_snapshot_id FOREIGN KEY (snapshot_id) REFERENCES year_end_balance_snapshot(id);
ALTER TABLE year_end_balance_snapshot_line ADD CONSTRAINT fk_year_end_balance_snapshot_line_member_id FOREIGN KEY (member_id) REFERENCES member(id);
-- Row-Level Security (multi_tenant_invariant)
ALTER TABLE alert ENABLE ROW LEVEL SECURITY;
CREATE POLICY alert_tenant_isolation ON alert
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE audit_log_entry ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_log_entry_tenant_isolation ON audit_log_entry
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE entity_version ENABLE ROW LEVEL SECURITY;
CREATE POLICY entity_version_tenant_isolation ON entity_version
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE interest_accrual ENABLE ROW LEVEL SECURITY;
CREATE POLICY interest_accrual_tenant_isolation ON interest_accrual
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE member ENABLE ROW LEVEL SECURITY;
CREATE POLICY member_tenant_isolation ON member
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE contribution_cycle ENABLE ROW LEVEL SECURITY;
CREATE POLICY contribution_cycle_tenant_isolation ON contribution_cycle
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE contribution ENABLE ROW LEVEL SECURITY;
CREATE POLICY contribution_tenant_isolation ON contribution
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE withdrawal ENABLE ROW LEVEL SECURITY;
CREATE POLICY withdrawal_tenant_isolation ON withdrawal
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE expense ENABLE ROW LEVEL SECURITY;
CREATE POLICY expense_tenant_isolation ON expense
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE slip_photo ENABLE ROW LEVEL SECURITY;
CREATE POLICY slip_photo_tenant_isolation ON slip_photo
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE account ENABLE ROW LEVEL SECURITY;
CREATE POLICY account_tenant_isolation ON account
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE transfer ENABLE ROW LEVEL SECURITY;
CREATE POLICY transfer_tenant_isolation ON transfer
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE extraordinary_collection ENABLE ROW LEVEL SECURITY;
CREATE POLICY extraordinary_collection_tenant_isolation ON extraordinary_collection
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE extraordinary_collection_line ENABLE ROW LEVEL SECURITY;
CREATE POLICY extraordinary_collection_line_tenant_isolation ON extraordinary_collection_line
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE loan ENABLE ROW LEVEL SECURITY;
CREATE POLICY loan_tenant_isolation ON loan
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE loan_schedule ENABLE ROW LEVEL SECURITY;
CREATE POLICY loan_schedule_tenant_isolation ON loan_schedule
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE loan_fee ENABLE ROW LEVEL SECURITY;
CREATE POLICY loan_fee_tenant_isolation ON loan_fee
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE repayment ENABLE ROW LEVEL SECURITY;
CREATE POLICY repayment_tenant_isolation ON repayment
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE group_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_config_tenant_isolation ON group_config
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE impersonation ENABLE ROW LEVEL SECURITY;
CREATE POLICY impersonation_tenant_isolation ON impersonation
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE user_org_membership ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_org_membership_tenant_isolation ON user_org_membership
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE reconciliation_cycle ENABLE ROW LEVEL SECURITY;
CREATE POLICY reconciliation_cycle_tenant_isolation ON reconciliation_cycle
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE period_close ENABLE ROW LEVEL SECURITY;
CREATE POLICY period_close_tenant_isolation ON period_close
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE statement_archive ENABLE ROW LEVEL SECURITY;
CREATE POLICY statement_archive_tenant_isolation ON statement_archive
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE surplus_governance_decision ENABLE ROW LEVEL SECURITY;
CREATE POLICY surplus_governance_decision_tenant_isolation ON surplus_governance_decision
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE year_end_share_out ENABLE ROW LEVEL SECURITY;
CREATE POLICY year_end_share_out_tenant_isolation ON year_end_share_out
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE year_end_share_out_line ENABLE ROW LEVEL SECURITY;
CREATE POLICY year_end_share_out_line_tenant_isolation ON year_end_share_out_line
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE year_end_balance_snapshot ENABLE ROW LEVEL SECURITY;
CREATE POLICY year_end_balance_snapshot_tenant_isolation ON year_end_balance_snapshot
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE year_end_balance_snapshot_line ENABLE ROW LEVEL SECURITY;
CREATE POLICY year_end_balance_snapshot_line_tenant_isolation ON year_end_balance_snapshot_line
  USING (org_id = current_setting('app.current_org_id', true)::uuid);

-- Append-only triggers (append_only_entities)
CREATE OR REPLACE FUNCTION alert_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on alert', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER alert_no_mutate
  BEFORE UPDATE OR DELETE ON alert
  FOR EACH ROW EXECUTE FUNCTION alert_append_only();

CREATE OR REPLACE FUNCTION audit_log_entry_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on audit_log_entry', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER audit_log_entry_no_mutate
  BEFORE UPDATE OR DELETE ON audit_log_entry
  FOR EACH ROW EXECUTE FUNCTION audit_log_entry_append_only();

CREATE OR REPLACE FUNCTION entity_version_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on entity_version', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER entity_version_no_mutate
  BEFORE UPDATE OR DELETE ON entity_version
  FOR EACH ROW EXECUTE FUNCTION entity_version_append_only();

CREATE OR REPLACE FUNCTION interest_accrual_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on interest_accrual', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER interest_accrual_no_mutate
  BEFORE UPDATE OR DELETE ON interest_accrual
  FOR EACH ROW EXECUTE FUNCTION interest_accrual_append_only();

CREATE OR REPLACE FUNCTION contribution_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on contribution', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER contribution_no_mutate
  BEFORE UPDATE OR DELETE ON contribution
  FOR EACH ROW EXECUTE FUNCTION contribution_append_only();

CREATE OR REPLACE FUNCTION withdrawal_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on withdrawal', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER withdrawal_no_mutate
  BEFORE UPDATE OR DELETE ON withdrawal
  FOR EACH ROW EXECUTE FUNCTION withdrawal_append_only();

CREATE OR REPLACE FUNCTION expense_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on expense', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER expense_no_mutate
  BEFORE UPDATE OR DELETE ON expense
  FOR EACH ROW EXECUTE FUNCTION expense_append_only();

CREATE OR REPLACE FUNCTION transfer_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on transfer', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER transfer_no_mutate
  BEFORE UPDATE OR DELETE ON transfer
  FOR EACH ROW EXECUTE FUNCTION transfer_append_only();

CREATE OR REPLACE FUNCTION extraordinary_collection_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on extraordinary_collection', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER extraordinary_collection_no_mutate
  BEFORE UPDATE OR DELETE ON extraordinary_collection
  FOR EACH ROW EXECUTE FUNCTION extraordinary_collection_append_only();

CREATE OR REPLACE FUNCTION extraordinary_collection_line_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on extraordinary_collection_line', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER extraordinary_collection_line_no_mutate
  BEFORE UPDATE OR DELETE ON extraordinary_collection_line
  FOR EACH ROW EXECUTE FUNCTION extraordinary_collection_line_append_only();

CREATE OR REPLACE FUNCTION repayment_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on repayment', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER repayment_no_mutate
  BEFORE UPDATE OR DELETE ON repayment
  FOR EACH ROW EXECUTE FUNCTION repayment_append_only();

CREATE OR REPLACE FUNCTION impersonation_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on impersonation', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER impersonation_no_mutate
  BEFORE UPDATE OR DELETE ON impersonation
  FOR EACH ROW EXECUTE FUNCTION impersonation_append_only();

CREATE OR REPLACE FUNCTION period_close_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on period_close', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER period_close_no_mutate
  BEFORE UPDATE OR DELETE ON period_close
  FOR EACH ROW EXECUTE FUNCTION period_close_append_only();

CREATE OR REPLACE FUNCTION statement_archive_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on statement_archive', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER statement_archive_no_mutate
  BEFORE UPDATE OR DELETE ON statement_archive
  FOR EACH ROW EXECUTE FUNCTION statement_archive_append_only();

-- period_lock_invariant (ledger immutability after PeriodClose).
-- Source: 04_entity_catalog.period_lock_invariant. The per-attribute
-- domain columns (dated_on, closed_at) now exist (IMP-250 column
-- enrichment), so the guard trigger CAN bind; wiring the trigger to the
-- concrete close column is a follow-up (the columns are no longer the blocker).