/// <reference lib="webworker" />
// sw.ts — Serwist service worker (generated by Nous, IMP-238).
// IMP-248 — the `webworker` lib reference above brings `ServiceWorkerGlobalScope`
// into scope (the project tsconfig targets DOM, not WebWorker), so `tsc`
// resolves the service-worker global type instead of TS2552.
import { defaultCache } from "@serwist/next/worker";
import { Serwist } from "serwist";

declare const self: ServiceWorkerGlobalScope & {
  __SW_MANIFEST: (string | { url: string; revision: string | null })[];
};

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: defaultCache,
});

serwist.addEventListeners();
