// index.ts — Drizzle client (generated by Nous).
//
// Runtime writes use transactions heavily. Drizzle's neon-http adapter does
// not support transaction(), so the app defaults to node-postgres even for
// Neon URLs. Use DB_DRIVER=neon-http only for explicit read-only/tooling paths.
import { drizzle as drizzlePg } from "drizzle-orm/node-postgres";
import { drizzle as drizzleNeon } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { Pool } from "pg";
import * as schema from "./schema";

const url = process.env.DATABASE_URL ?? "";
const driver = process.env.DB_DRIVER;

export function shouldUseNeonHttp(driver: string | undefined): boolean {
  return driver === "neon-http";
}

export const db = shouldUseNeonHttp(driver)
  ? drizzleNeon({ client: neon(url), schema })
  : drizzlePg({ client: new Pool({ connectionString: url }), schema });
