// schema.ts — Drizzle pgTable schema (generated by Nous, IMP-250).
// Tables + columns (types/enums/money/uniqueness) + FK/org_id derive
// from the project's 04_entity_catalog entity_attributes.
import { boolean, date, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";

export const account_status_enum = pgEnum("account_status_enum", ["active", "archived"]);
export const account_type_enum = pgEnum("account_type_enum", ["group_bank", "cash_box", "treasurer_personal", "external"]);
export const alert_audience_enum = pgEnum("alert_audience_enum", ["treasurer", "platform_operator", "both"]);
export const alert_severity_enum = pgEnum("alert_severity_enum", ["low", "medium", "high", "critical"]);
export const audit_log_entry_actor_kind_enum = pgEnum("audit_log_entry_actor_kind_enum", ["member", "platform_operator", "system"]);
export const contribution_cycle_created_by_kind_enum = pgEnum("contribution_cycle_created_by_kind_enum", ["system", "member"]);
export const contribution_cycle_status_enum = pgEnum("contribution_cycle_status_enum", ["open", "closed"]);
export const entity_version_change_kind_enum = pgEnum("entity_version_change_kind_enum", ["create", "update", "status_transition"]);
export const entity_version_created_by_kind_enum = pgEnum("entity_version_created_by_kind_enum", ["member", "platform_operator", "system"]);
export const expense_status_enum = pgEnum("expense_status_enum", ["planned", "paid"]);
export const extraordinary_collection_line_reconciliation_status_enum = pgEnum("extraordinary_collection_line_reconciliation_status_enum", ["pending", "regularized"]);
export const group_config_contribution_cycle_kind_enum = pgEnum("group_config_contribution_cycle_kind_enum", ["monthly", "weekly"]);
export const group_config_created_by_kind_enum = pgEnum("group_config_created_by_kind_enum", ["platform_operator", "member"]);
export const group_config_repayment_split_rule_enum = pgEnum("group_config_repayment_split_rule_enum", ["interest_first", "principal_first", "even_split"]);
export const institution_kind_enum = pgEnum("institution_kind_enum", ["bank", "coop", "other"]);
export const institution_status_enum = pgEnum("institution_status_enum", ["active", "inactive"]);
export const loan_schedule_status_enum = pgEnum("loan_schedule_status_enum", ["pendiente", "parcial", "pagado", "atrasado", "en_mora"]);
export const loan_status_enum = pgEnum("loan_status_enum", ["proposed", "originated", "activo", "pagado", "cancelado", "en_mora"]);
export const member_role_enum = pgEnum("member_role_enum", ["aportante", "tesorera", "presidente", "secretaria"]);
export const member_status_enum = pgEnum("member_status_enum", ["activo", "en_pausa", "baja"]);
export const organization_status_enum = pgEnum("organization_status_enum", ["active", "paused", "archived"]);
export const platform_operator_status_enum = pgEnum("platform_operator_status_enum", ["active", "disabled"]);
export const reconciliation_cycle_resolution_kind_enum = pgEnum("reconciliation_cycle_resolution_kind_enum", ["auto_within_tolerance", "resolved_by_correction", "annotated_acceptance"]);
export const slip_photo_attached_to_kind_enum = pgEnum("slip_photo_attached_to_kind_enum", ["contribution", "repayment"]);
export const statement_archive_kind_enum = pgEnum("statement_archive_kind_enum", ["monthly_close", "monthly_member", "year_end_member", "year_end_share_out", "year_end_snapshot", "balance_banquito", "year_end_economic_summary", "monthly_summary"]);
export const surplus_governance_decision_status_enum = pgEnum("surplus_governance_decision_status_enum", ["draft", "approved", "locked"]);
export const user_account_status_enum = pgEnum("user_account_status_enum", ["active", "disabled"]);
export const user_org_membership_status_enum = pgEnum("user_org_membership_status_enum", ["active", "revoked"]);
export const withdrawal_created_by_kind_enum = pgEnum("withdrawal_created_by_kind_enum", ["member", "system"]);
export const withdrawal_kind_enum = pgEnum("withdrawal_kind_enum", ["member_refund", "year_end_share_out", "other"]);
export const year_end_share_out_status_enum = pgEnum("year_end_share_out_status_enum", ["draft", "approved", "distributed", "locked"]);

export const alert = pgTable("alert", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id"),
  alertKind: text("alert_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  severity: alert_severity_enum("severity").notNull(),
  audience: alert_audience_enum("audience").notNull(),
  subjectKind: text("subject_kind"),
  subjectId: uuid("subject_id"),
  payload: jsonb("payload").notNull(),
  dedupWindowEnd: timestamp("dedup_window_end").notNull(),
  dismissedAt: timestamp("dismissed_at"),
  dismissedBy: uuid("dismissed_by"),
  snoozedUntil: timestamp("snoozed_until"),
  createdAt: timestamp("created_at").notNull(),
});

export const auditLogEntry = pgTable("audit_log_entry", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id"),
  actorKind: audit_log_entry_actor_kind_enum("actor_kind").notNull(),
  actorId: uuid("actor_id").notNull(),
  actionKind: text("action_kind").notNull(),
  subjectKind: text("subject_kind").notNull(),
  subjectId: uuid("subject_id"),
  payloadSnapshot: jsonb("payload_snapshot").notNull(),
  reason: text("reason"),
  at: timestamp("at").notNull(),
  createdAt: timestamp("created_at").notNull(),
});

export const entityVersion = pgTable("entity_version", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id"),
  entityKind: text("entity_kind").notNull(),
  entityId: uuid("entity_id").notNull(),
  version: integer("version").notNull(),
  validFrom: timestamp("valid_from").notNull(),
  validTo: timestamp("valid_to"),
  payloadSnapshot: jsonb("payload_snapshot").notNull(),
  changeKind: entity_version_change_kind_enum("change_kind").notNull(),
  changeReason: text("change_reason"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: entity_version_created_by_kind_enum("created_by_kind").notNull(),
});

export const interestAccrual = pgTable("interest_accrual", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  loanId: uuid("loan_id").references((): AnyPgColumn => loan.id).notNull(),
  accruedOn: date("accrued_on").notNull(),
  principalBasis: numeric("principal_basis", { precision: 18, scale: 4 }).notNull(),
  periodDays: integer("period_days").notNull(),
  rateValue: numeric("rate_value", { precision: 8, scale: 4 }).notNull(),
  interestAmount: numeric("interest_amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  recordedAt: timestamp("recorded_at").notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const member = pgTable("member", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  displayName: text("display_name").notNull(),
  whatsappNumber: text("whatsapp_number"),
  joinedOn: date("joined_on").notNull(),
  role: member_role_enum("role").notNull(),
  status: member_status_enum("status").notNull(),
  authSubject: text("auth_subject"),
  initialSavingsBalance: numeric("initial_savings_balance", { precision: 18, scale: 4 }).notNull(),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  updatedAt: timestamp("updated_at"),
  updatedBy: uuid("updated_by"),
});

export const contributionCycle = pgTable("contribution_cycle", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  cycleLabel: text("cycle_label").notNull(),
  kind: text("kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  opensOn: date("opens_on").notNull(),
  closesOn: date("closes_on").notNull(),
  expectedAmountPerMember: numeric("expected_amount_per_member", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  status: contribution_cycle_status_enum("status").notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: contribution_cycle_created_by_kind_enum("created_by_kind").notNull(),
});

export const contribution = pgTable("contribution", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  cycleId: uuid("cycle_id").references((): AnyPgColumn => contributionCycle.id).notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  datedOn: date("dated_on").notNull(),
  recordedAt: timestamp("recorded_at").notNull(),
  slipPhotoId: uuid("slip_photo_id").references((): AnyPgColumn => slipPhoto.id),
  notes: text("notes"),
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  reverseReason: text("reverse_reason"),
  clientRequestId: uuid("client_request_id"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const withdrawal = pgTable("withdrawal", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  datedOn: date("dated_on").notNull(),
  recordedAt: timestamp("recorded_at").notNull(),
  kind: withdrawal_kind_enum("kind").notNull(),
  shareOutId: uuid("share_out_id").references((): AnyPgColumn => yearEndShareOut.id),
  notes: text("notes"),
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  reverseReason: text("reverse_reason"),
  clientRequestId: uuid("client_request_id"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: withdrawal_created_by_kind_enum("created_by_kind").notNull(),
  yearEndShareOutLineId: uuid("year_end_share_out_line_id").references((): AnyPgColumn => yearEndShareOutLine.id),
});

export const expense = pgTable("expense", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  purpose: text("purpose").notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  beneficiaryMemberId: uuid("beneficiary_member_id").references((): AnyPgColumn => member.id),
  beneficiaryText: text("beneficiary_text"),
  incurredOn: date("incurred_on").notNull(),
  status: expense_status_enum("status").notNull(),
  recordedAt: timestamp("recorded_at").notNull(),
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  reverseReason: text("reverse_reason"),
  clientRequestId: uuid("client_request_id"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const slipPhoto = pgTable("slip_photo", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  uri: text("uri").notNull(),
  mimeType: text("mime_type").notNull(),
  byteSize: integer("byte_size").notNull(),
  attachedToKind: slip_photo_attached_to_kind_enum("attached_to_kind").notNull(),
  attachedToId: uuid("attached_to_id").notNull(),
  uploadedAt: timestamp("uploaded_at").notNull(),
  uploadedBy: uuid("uploaded_by").notNull(),
  uploadedByKind: text("uploaded_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  contributionId: uuid("contribution_id").references((): AnyPgColumn => contribution.id),
  repaymentId: uuid("repayment_id").references((): AnyPgColumn => repayment.id),
});

export const account = pgTable("account", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  name: text("name").notNull(),
  type: account_type_enum("type").notNull(),
  isGroupFund: boolean("is_group_fund").notNull(),
  last4: text("last4"),
  productType: text("product_type"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  institutionId: uuid("institution_id").references((): AnyPgColumn => institution.id),
  status: account_status_enum("status").notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
});

export const transfer = pgTable("transfer", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  fromAccountId: uuid("from_account_id").references((): AnyPgColumn => account.id).notNull(),
  toAccountId: uuid("to_account_id").references((): AnyPgColumn => account.id).notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  datedOn: date("dated_on").notNull(),
  purpose: text("purpose"),
  regularizesKind: text("regularizes_kind"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  regularizesId: uuid("regularizes_id"),
  slipPhotoId: uuid("slip_photo_id").references((): AnyPgColumn => slipPhoto.id),
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
});

export const extraordinaryCollection = pgTable("extraordinary_collection", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  kind: text("kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  purpose: text("purpose").notNull(),
  beneficiaryMemberId: uuid("beneficiary_member_id").references((): AnyPgColumn => member.id),
  targetAmount: numeric("target_amount", { precision: 18, scale: 4 }),
  status: text("status").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  openedOn: date("opened_on").notNull(),
  paidOutExpenseId: uuid("paid_out_expense_id").references((): AnyPgColumn => expense.id),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
});

export const extraordinaryCollectionLine = pgTable("extraordinary_collection_line", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  collectionId: uuid("collection_id").references((): AnyPgColumn => extraordinaryCollection.id).notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id),
  reconciliationStatus: extraordinary_collection_line_reconciliation_status_enum("reconciliation_status").notNull(),
  datedOn: date("dated_on").notNull(),
  slipPhotoId: uuid("slip_photo_id").references((): AnyPgColumn => slipPhoto.id),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
});

export const loan = pgTable("loan", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  principalAmount: numeric("principal_amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  rateValue: numeric("rate_value", { precision: 8, scale: 4 }).notNull(),
  rateModel: text("rate_model").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  termPeriods: integer("term_periods").notNull(),
  gracePeriods: integer("grace_periods").notNull(),
  originatedOn: date("originated_on").notNull(),
  status: loan_status_enum("status").notNull(),
  purpose: text("purpose"),
  clientRequestId: uuid("client_request_id"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  updatedAt: timestamp("updated_at"),
  updatedBy: uuid("updated_by"),
});

export const loanSchedule = pgTable("loan_schedule", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  loanId: uuid("loan_id").references((): AnyPgColumn => loan.id).notNull(),
  periodIndex: integer("period_index").notNull(),
  dueOn: date("due_on").notNull(),
  principalDue: numeric("principal_due", { precision: 18, scale: 4 }).notNull(),
  interestDue: numeric("interest_due", { precision: 18, scale: 4 }).notNull(),
  status: loan_schedule_status_enum("status").notNull(),
  paidPrincipalToDate: numeric("paid_principal_to_date", { precision: 18, scale: 4 }).notNull(),
  paidInterestToDate: numeric("paid_interest_to_date", { precision: 18, scale: 4 }).notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const loanFee = pgTable("loan_fee", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  loanId: uuid("loan_id").references((): AnyPgColumn => loan.id).notNull(),
  loanScheduleId: uuid("loan_schedule_id").references((): AnyPgColumn => loanSchedule.id),
  feeKind: text("fee_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  datedOn: date("dated_on").notNull(),
  accruedOn: date("accrued_on").notNull(),
  groupConfigVersion: integer("group_config_version").notNull(),
  feedsSurplus: boolean("feeds_surplus").notNull(),
  accountId: uuid("account_id").references((): AnyPgColumn => account.id),
  reconciliationStatus: text("reconciliation_status"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  reverseReason: text("reverse_reason"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const repayment = pgTable("repayment", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  loanId: uuid("loan_id").references((): AnyPgColumn => loan.id).notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  appliedToPrincipal: numeric("applied_to_principal", { precision: 18, scale: 4 }).notNull(),
  appliedToInterest: numeric("applied_to_interest", { precision: 18, scale: 4 }).notNull(),
  datedOn: date("dated_on").notNull(),
  recordedAt: timestamp("recorded_at").notNull(),
  slipPhotoId: uuid("slip_photo_id").references((): AnyPgColumn => slipPhoto.id),
  notes: text("notes"),
  reversesId: uuid("reverses_id"),  // self-ref FK (constraint in migration)
  reverseReason: text("reverse_reason"),
  clientRequestId: uuid("client_request_id"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const organization = pgTable("organization", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  displayName: text("display_name").notNull(),
  countryCode: text("country_code").notNull(),
  currencyCode: text("currency_code").notNull(),
  timezone: text("timezone").notNull(),
  defaultLanguage: text("default_language").notNull(),
  status: organization_status_enum("status").notNull(),
  brandingLogoUri: text("branding_logo_uri"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  updatedAt: timestamp("updated_at"),
  updatedBy: uuid("updated_by"),
  platformOperatorId: uuid("platform_operator_id").references((): AnyPgColumn => platformOperator.id),
});

export const groupConfig = pgTable("group_config", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  version: integer("version").notNull(),
  validFrom: timestamp("valid_from").notNull(),
  validTo: timestamp("valid_to"),
  contributionCycleKind: group_config_contribution_cycle_kind_enum("contribution_cycle_kind").notNull(),
  contributionAmount: numeric("contribution_amount", { precision: 18, scale: 4 }).notNull(),
  currencyCode: text("currency_code").notNull(),
  loanRateModel: text("loan_rate_model").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  loanRateValue: numeric("loan_rate_value", { precision: 8, scale: 4 }).notNull(),
  loanGracePeriods: integer("loan_grace_periods").notNull(),
  loanToSavingsCapRatio: numeric("loan_to_savings_cap_ratio", { precision: 4, scale: 2 }).notNull(),
  interestResolution: text("interest_resolution").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  repaymentSplitRule: group_config_repayment_split_rule_enum("repayment_split_rule").notNull(),
  paysSavingsInterest: boolean("pays_savings_interest").notNull(),
  savingsInterestRate: numeric("savings_interest_rate", { precision: 8, scale: 4 }),
  yearEndShareOutFormula: text("year_end_share_out_formula"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  safetyMarginAmount: numeric("safety_margin_amount", { precision: 18, scale: 4 }).notNull(),
  reconciliationToleranceAmount: numeric("reconciliation_tolerance_amount", { precision: 18, scale: 4 }).notNull(),
  lateThresholdDays: integer("late_threshold_days").notNull(),
  moraThresholdDays: integer("mora_threshold_days").notNull(),
  config: jsonb("config").notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: group_config_created_by_kind_enum("created_by_kind").notNull(),
});

export const platformOperator = pgTable("platform_operator", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  displayName: text("display_name").notNull(),
  email: text("email").notNull(),
  authSubject: text("auth_subject"),
  status: platform_operator_status_enum("status").notNull(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});

export const impersonation = pgTable("impersonation", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  platformOperatorId: uuid("platform_operator_id").references((): AnyPgColumn => platformOperator.id).notNull(),
  startedAt: timestamp("started_at").notNull(),
  endedAt: timestamp("ended_at"),
  reason: text("reason").notNull(),
  mode: text("mode").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  createdAt: timestamp("created_at").notNull(),
});

export const userAccount = pgTable("user_account", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  authSubject: text("auth_subject").notNull(),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  status: user_account_status_enum("status").notNull(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});

export const userOrgMembership = pgTable("user_org_membership", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  userId: uuid("user_id").references((): AnyPgColumn => userAccount.id).notNull(),
  orgId: uuid("org_id").notNull(),
  role: text("role").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  status: user_org_membership_status_enum("status").notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id),
  grantedAt: timestamp("granted_at").notNull(),
  revokedAt: timestamp("revoked_at"),
});

export const country = pgTable("country", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  iso2: text("iso2").notNull(),
  iso3: text("iso3").notNull(),
  name: text("name").notNull(),
  currencyCode: text("currency_code").notNull(),
  createdAt: timestamp("created_at").notNull(),
});

export const institution = pgTable("institution", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  countryId: uuid("country_id").references((): AnyPgColumn => country.id).notNull(),
  name: text("name").notNull(),
  kind: institution_kind_enum("kind").notNull(),
  swiftBic: text("swift_bic"),
  status: institution_status_enum("status").notNull(),
  createdAt: timestamp("created_at").notNull(),
});

export const reconciliationCycle = pgTable("reconciliation_cycle", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  cycleId: uuid("cycle_id").references((): AnyPgColumn => contributionCycle.id).notNull(),
  declaredBankBalance: numeric("declared_bank_balance", { precision: 18, scale: 4 }).notNull(),
  computedPoolBalance: numeric("computed_pool_balance", { precision: 18, scale: 4 }).notNull(),
  discrepancyAmount: numeric("discrepancy_amount", { precision: 18, scale: 4 }).notNull(),
  toleranceAmount: numeric("tolerance_amount", { precision: 18, scale: 4 }).notNull(),
  resolutionKind: reconciliation_cycle_resolution_kind_enum("resolution_kind").notNull(),
  resolutionNote: text("resolution_note"),
  closedAt: timestamp("closed_at"),
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const periodClose = pgTable("period_close", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  cycleId: uuid("cycle_id").references((): AnyPgColumn => contributionCycle.id).notNull(),
  reconciliationCycleId: uuid("reconciliation_cycle_id").references((): AnyPgColumn => reconciliationCycle.id).notNull(),
  closedAt: timestamp("closed_at").notNull(),
  closedBy: uuid("closed_by").notNull(),
  closedByKind: text("closed_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  isYearEnd: boolean("is_year_end").notNull(),
  monthlyCloseStatementId: uuid("monthly_close_statement_id").references((): AnyPgColumn => statementArchive.id),
  createdAt: timestamp("created_at").notNull(),
});

export const statementArchive = pgTable("statement_archive", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  kind: statement_archive_kind_enum("kind").notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id),
  periodLabel: text("period_label").notNull(),
  pdfUri: text("pdf_uri").notNull(),
  canonicalPayloadHash: text("canonical_payload_hash").notNull(),
  generatedAt: timestamp("generated_at").notNull(),
  periodCloseId: uuid("period_close_id").references((): AnyPgColumn => periodClose.id),
  yearEndShareOutId: uuid("year_end_share_out_id").references((): AnyPgColumn => yearEndShareOut.id),
  byteSize: integer("byte_size").notNull(),
  createdAt: timestamp("created_at").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const surplusGovernanceDecision = pgTable("surplus_governance_decision", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  year: integer("year").notNull(),
  version: integer("version").notNull(),
  validFrom: timestamp("valid_from").notNull(),
  validTo: timestamp("valid_to"),
  distributableSurplus: numeric("distributable_surplus", { precision: 18, scale: 4 }).notNull(),
  repartoTotal: numeric("reparto_total", { precision: 18, scale: 4 }).notNull(),
  reservaAmount: numeric("reserva_amount", { precision: 18, scale: 4 }).notNull(),
  reservaDisposition: text("reserva_disposition").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  loanPoolPct: numeric("loan_pool_pct", { precision: 6, scale: 4 }).notNull(),
  savingsPoolPct: numeric("savings_pool_pct", { precision: 6, scale: 4 }).notNull(),
  status: surplus_governance_decision_status_enum("status").notNull(),
  decidedAt: timestamp("decided_at"),
  decidedBy: uuid("decided_by").notNull(),
  decidedByKind: text("decided_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  createdAt: timestamp("created_at").notNull(),
});

export const yearEndShareOut = pgTable("year_end_share_out", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  year: integer("year").notNull(),
  periodCloseId: uuid("period_close_id").references((): AnyPgColumn => periodClose.id).notNull(),
  formulaAtRun: text("formula_at_run"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  totalPoolAtRun: numeric("total_pool_at_run", { precision: 18, scale: 4 }).notNull(),
  totalCommitment: numeric("total_commitment", { precision: 18, scale: 4 }).notNull(),
  totalApproved: numeric("total_approved", { precision: 18, scale: 4 }),
  surplusOrShortfallAtApproval: numeric("surplus_or_shortfall_at_approval", { precision: 18, scale: 4 }),
  governanceDecisionId: uuid("governance_decision_id").references((): AnyPgColumn => surplusGovernanceDecision.id),
  distributableSurplus: numeric("distributable_surplus", { precision: 18, scale: 4 }),
  cxcAnterior: numeric("cxc_anterior", { precision: 18, scale: 4 }),
  repartoTotal: numeric("reparto_total", { precision: 18, scale: 4 }),
  loanPoolAmount: numeric("loan_pool_amount", { precision: 18, scale: 4 }),
  savingsPoolAmount: numeric("savings_pool_amount", { precision: 18, scale: 4 }),
  alicuotaPrestamos: numeric("alicuota_prestamos", { precision: 12, scale: 10 }),
  alicuotaAhorros: numeric("alicuota_ahorros", { precision: 12, scale: 10 }),
  ajusteAmount: numeric("ajuste_amount", { precision: 18, scale: 4 }),
  status: year_end_share_out_status_enum("status").notNull(),
  approvedAt: timestamp("approved_at"),
  approvedBy: uuid("approved_by"),
  approvedByKind: text("approved_by_kind"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  createdAt: timestamp("created_at").notNull(),
  createdBy: uuid("created_by").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const yearEndShareOutLine = pgTable("year_end_share_out_line", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  yearEndShareOutId: uuid("year_end_share_out_id").references((): AnyPgColumn => yearEndShareOut.id).notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  accumulatedSavingsAtRun: numeric("accumulated_savings_at_run", { precision: 18, scale: 4 }).notNull(),
  loanActivityBasis: numeric("loan_activity_basis", { precision: 18, scale: 4 }),
  loanBonusC: numeric("loan_bonus_c", { precision: 18, scale: 4 }),
  savingsInterest: numeric("savings_interest", { precision: 18, scale: 4 }),
  draftShareAmount: numeric("draft_share_amount", { precision: 18, scale: 4 }).notNull(),
  overrideShareAmount: numeric("override_share_amount", { precision: 18, scale: 4 }),
  overrideReason: text("override_reason"),
  finalShareAmount: numeric("final_share_amount", { precision: 18, scale: 4 }).notNull(),
  disposition: text("disposition"),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
  dispositionMotive: text("disposition_motive"),
  withdrawalId: uuid("withdrawal_id").references((): AnyPgColumn => withdrawal.id),
  retainedContributionId: uuid("retained_contribution_id").references((): AnyPgColumn => contribution.id),
  memberStatementId: uuid("member_statement_id").references((): AnyPgColumn => statementArchive.id),
  createdAt: timestamp("created_at").notNull(),
});

export const yearEndBalanceSnapshot = pgTable("year_end_balance_snapshot", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  year: integer("year").notNull(),
  snapshotDate: date("snapshot_date").notNull(),
  periodCloseId: uuid("period_close_id").references((): AnyPgColumn => periodClose.id).notNull(),
  priorSnapshotId: uuid("prior_snapshot_id"),  // self-ref FK (constraint in migration)
  totalAhorros: numeric("total_ahorros", { precision: 18, scale: 4 }).notNull(),
  totalCuotaAcumulada: numeric("total_cuota_acumulada", { precision: 18, scale: 4 }).notNull(),
  totalPrestamosPorCobrar: numeric("total_prestamos_por_cobrar", { precision: 18, scale: 4 }).notNull(),
  totalInteresPorCobrar: numeric("total_interes_por_cobrar", { precision: 18, scale: 4 }).notNull(),
  bancoBalance: numeric("banco_balance", { precision: 18, scale: 4 }).notNull(),
  cxcAnterior: numeric("cxc_anterior", { precision: 18, scale: 4 }).notNull(),
  groupConfigVersion: integer("group_config_version").notNull(),
  canonicalPayloadHash: text("canonical_payload_hash").notNull(),
  statementArchiveId: uuid("statement_archive_id").references((): AnyPgColumn => statementArchive.id),
  createdAt: timestamp("created_at").notNull(),
  createdByKind: text("created_by_kind").notNull(),  // TODO[IMP-250]: enum members not cleanly parseable — text fallback
});

export const yearEndBalanceSnapshotLine = pgTable("year_end_balance_snapshot_line", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  orgId: uuid("org_id").notNull(),
  snapshotId: uuid("snapshot_id").references((): AnyPgColumn => yearEndBalanceSnapshot.id).notNull(),
  memberId: uuid("member_id").references((): AnyPgColumn => member.id).notNull(),
  ahorrosBalance: numeric("ahorros_balance", { precision: 18, scale: 4 }).notNull(),
  cuotaAcumulada: numeric("cuota_acumulada", { precision: 18, scale: 4 }).notNull(),
  prestamosPorCobrar: numeric("prestamos_por_cobrar", { precision: 18, scale: 4 }).notNull(),
  interesPorCobrar: numeric("interes_por_cobrar", { precision: 18, scale: 4 }).notNull(),
  createdAt: timestamp("created_at").notNull(),
});
