// middleware.ts — Auth0 Organizations route guard (generated by Nous, IMP-238).
import type { NextRequest } from "next/server";
import { auth0 } from "@/lib/auth0";

export async function middleware(request: NextRequest) {
  // Auth0 mounts /auth/* (login, logout, callback) and attaches the
  // session; organization context is enforced per-route below.
  return auth0.middleware(request);
}

export const config = {
  // Run on everything except static assets + the Auth0 mount itself.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|auth).*)"],
};
