#!/usr/bin/env node
// mutation-scope — diff-scoped Stryker run (generated by Nous, IMP-344 / L1).
//
// ONE campaign over the files this branch actually changed, instead of a
// whole-tree run or a hand-chained per-story sequence. The common case — a diff
// with nothing mutatable — exits 0 in milliseconds without starting Stryker.
//
// Scope is the DIFF, filtered to mutatable source files. Deliberately NOT
// intersected with the critical set: nothing declares critical source *paths*,
// and guessing them could only drop a changed critical file from the run. The
// critical set decides which STORIES owe mutation evidence (see
// docs/dev-guide/TESTING.md §3), not which files get mutated.
//
// Env overrides:
//   MUTATION_BASE=<ref>   compare against this ref instead of the default branch
//   MUTATION_SCOPE_DRY=1  write + print the generated config, do NOT run Stryker
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const BASE_CONFIG = "stryker.conf.json";
const GENERATED_CONFIG = join(".tmp", "stryker.generated.conf.json");

// Mirrors stryker.conf.json's mutate globs: which files can carry mutants.
// This is a FILE-TYPE filter, not a critical-set narrowing — a changed `.md` or
// `.json` has no mutants, so excluding it removes nothing real.
const MUTATABLE_EXT = /\.(ts|tsx)$/;

// Build output. `--exclude-standard` already honours .gitignore, so this is the
// belt-and-braces layer for a package whose ignore file is thin. `.tmp/` is not
// optional paranoia: THIS SCRIPT writes `.tmp/stryker.generated.conf.json`, so
// without the exclusion an untracked-file scan can feed the run its own output.
const GENERATED_ARTIFACT = [
  /(^|\/)\.tmp\//,
  /(^|\/)\.next\//,
  /(^|\/)(coverage|dist|reports)\//,
];

const EXCLUDED = [
  /\.(test|spec)\.tsx?$/,
  /\.d\.ts$/,
  /(^|\/)migrations\//,
  /(^|\/)testing\//,
  /(^|\/)node_modules\//,
  ...GENERATED_ARTIFACT,
];

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

/** A git call whose FAILURE is an expected, handled outcome (probing for a ref
 *  that may not exist). git writes `fatal: ...` to stderr even when the caller
 *  copes, so stderr is discarded here — otherwise every run in a repo without
 *  `origin/HEAD` prints a scary line that is not an error. Real failures still
 *  surface: the caller decides, via the thrown exception. */
function gitProbe(args) {
  return execFileSync("git", args, {
    encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

/** Fail LOUD. A mutation run that cannot determine its scope must NOT report
 *  success having mutated nothing — a silent empty scope is a false green. */
function fail(message, hint) {
  console.error(`mutation-scope: ${message}`);
  if (hint) console.error(`  ${hint}`);
  process.exit(2);
}

/** The ref to diff against. Resolved, never hardcoded to `main`: a repo whose
 *  trunk is `master`, or a CI checkout with a different default, must not
 *  silently produce an empty diff. */
function resolveBase() {
  if (process.env.MUTATION_BASE) {
    const ref = process.env.MUTATION_BASE;
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch {
      fail(`MUTATION_BASE=${ref} does not resolve to a ref`,
           "check the ref name, or unset MUTATION_BASE to use the default branch");
    }
  }
  try {
    // origin/HEAD is the authoritative default branch when a remote exists.
    const sym = gitProbe(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]);
    if (sym) return sym;
  } catch { /* no remote / no origin/HEAD — fall through to local trunks */ }
  for (const ref of ["main", "master"]) {
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch { /* try the next candidate */ }
  }
  fail("cannot resolve a default branch to diff against (tried origin/HEAD, main, master)",
       "set MUTATION_BASE=<ref> explicitly");
}

function changedFiles(base) {
  let mergeBase;
  try {
    mergeBase = gitProbe(["merge-base", "HEAD", base]);
  } catch {
    // A shallow clone or an unrelated history has no merge base. Exiting 0 here
    // would mutate nothing and report success — the false green this guard
    // exists to prevent.
    fail(`no merge base between HEAD and ${base}`,
         "unshallow the clone (git fetch --unshallow) or set MUTATION_BASE=<ref>");
  }
  // ACMR excludes deletions: Stryker cannot mutate a file that is gone.
  //
  // Diff the merge base against the WORKING TREE, not `${mergeBase}..HEAD`. That
  // range compares two COMMITS and cannot see a working tree, but the Definition
  // of Done tells the developer to run this while CLOSING a story — before the
  // final commit. Scoped that way the gate is blind at exactly the moment it is
  // invoked, finds nothing, and exits 0: a green over code it never mutated,
  // which HR-48 then records as mutation evidence. Git does not report untracked
  // files at all, so those are added explicitly — otherwise a newly created
  // production module escapes the gate permanently (IMP-361).
  //
  // In CI this is equivalent to the old form: a clean tree checked out at a
  // commit has nothing staged, unstaged, or untracked to add.
  const tracked = git(["diff", "--name-only", "--diff-filter=ACMR", mergeBase]);
  const untracked = git(["ls-files", "--others", "--exclude-standard"]);
  return [...new Set(
    [tracked, untracked]
      .flatMap((value) => value ? value.split("\n") : [])
      .filter(Boolean)
      .filter((path) => !GENERATED_ARTIFACT.some((pattern) => pattern.test(path))),
  )].sort();  // deterministic: the generated config must be byte-stable
}

function mutatable(files) {
  return files
    .filter((f) => MUTATABLE_EXT.test(f))
    .filter((f) => !EXCLUDED.some((re) => re.test(f)))
    .sort();  // deterministic: the generated config must be byte-stable
}

/** Registered git worktrees nested INSIDE this repo, as Stryker ignorePatterns.
 *
 *  Stryker copies the whole project tree into its sandbox regardless of `mutate`
 *  (`mutate` says what carries mutants, not what gets COPIED), so a nested
 *  checkout is a second full copy of the repo — 1,184 files on one tenant, whose
 *  generated HTML also fails the type-check preprocessor. `.gitignore` does not
 *  help: Stryker never reads it.
 *
 *  ASKED OF GIT, NOT MATCHED BY NAME, and that is the whole design:
 *
 *  * There is no worktree directory convention. `.worktrees/` is one dev team's
 *    choice; the substrate declares none and must not invent one — a static
 *    `.worktrees` entry in `stryker.conf.json` was considered and REJECTED for
 *    exactly that reason (see the `ignorePatterns` comment above, and note that
 *    every entry there traces to a substrate-emitted `.gitignore` line, which
 *    `.worktrees` cannot). Git knows the path whatever it is called.
 *  * No nested worktree ⇒ empty list ⇒ a BYTE-IDENTICAL generated config. The
 *    change is inert for tenants that don't use worktrees, which is why it needs
 *    no activation gate.
 *  * Worktrees OUTSIDE the root are filtered out, not excluded: they are already
 *    outside the sandbox, so a pattern for them would match nothing.
 *
 *  THE LEADING "/" IS LOAD-BEARING. These are gitignore semantics: a pattern with
 *  no interior separator matches a path SEGMENT AT ANY DEPTH. A worktree at a
 *  single-segment path (`wt/`) emitted bare would therefore also exclude
 *  `packages/foo/wt/src/a.ts` — real source. Anchored it cannot. Verified against
 *  the real engine (`ignore@7.0.6`, the package Stryker feeds ignoreRules to):
 *
 *    pattern   wt/apps/web/a.ts   packages/foo/wt/src/a.ts
 *    wt        IGNORED            IGNORED  ← over-reach
 *    /wt       IGNORED            kept
 *
 *  A worktree path is a KNOWN path, so anchoring it is exact — the mirror of why
 *  `.turbo` is bare up in `stryker.conf.json`, where the target is a NAME at an
 *  unknown depth. Do not "tidy" either one into the other's form. */
function nestedCheckouts() {
  const root = git(["rev-parse", "--show-toplevel"]);
  return git(["worktree", "list", "--porcelain"])
    .split("\n")
    .filter((line) => line.startsWith("worktree "))
    .map((line) => line.slice("worktree ".length))
    .filter((path) => path !== root && path.startsWith(`${root}/`))
    .map((path) => `/${relative(root, path)}`)
    .sort();  // deterministic: the generated config must be byte-stable
}

function main() {
  const base = resolveBase();
  const changed = changedFiles(base);
  const mutate = mutatable(changed);

  console.log(`mutation-scope: base=${base} changed=${changed.length} mutatable=${mutate.length}`);

  if (mutate.length === 0) {
    console.log("mutation-scope: no mutatable files in diff — nothing to mutate");
    process.exit(0);
  }

  // IMP-360 / L3 — absent and unreadable are different problems with different
  // fixes, and collapsing them cost a real debugging cycle: a tenant whose
  // toolchain sync delivered THIS script but not its config was told to check
  // its working directory, which was already correct. Existence is established
  // by existsSync, never by the catch — the same rule `read_owned_configs` uses
  // on the substrate side, for the same reason.
  let baseConf = {};
  if (!existsSync(BASE_CONFIG)) {
    fail(`${BASE_CONFIG} is missing`,
         "the substrate emits it — deliver it with: " +
         "python3 nous_package.py sync --target <pkg> --categories toolchain");
  }
  try {
    baseConf = JSON.parse(readFileSync(BASE_CONFIG, "utf8"));
  } catch {
    fail(`cannot read ${BASE_CONFIG}`, "run from the repository root");
  }

  // tempDirName is derived from the SCOPE, not the clock: two runs on the same
  // diff must produce a byte-identical config, and two runs on different scopes
  // must not collide.
  const digest = createHash("sha256").update(mutate.join("\n")).digest("hex").slice(0, 12);

  // COMPOSE with the base config's patterns, never substitute: the static half
  // (build output, generated docs) and the dynamic half (nested checkouts) solve
  // different problems and neither subsumes the other. Base first, so with no
  // nested worktree the value is identical to what the spread already carried.
  const ignorePatterns = [...(baseConf.ignorePatterns ?? []), ...nestedCheckouts()];

  const conf = {
    ...baseConf,
    mutate,
    // Emitted ONLY when non-empty, so a base config that declares no
    // ignorePatterns and a repo with no nested worktree still produce a
    // BYTE-IDENTICAL config — an unconditional assignment would introduce
    // `"ignorePatterns": []` where there was no key at all. Where the key does
    // exist, re-assigning it keeps its original position in the spread, so key
    // order (and therefore the serialized bytes) is unchanged either way.
    ...(ignorePatterns.length > 0 ? { ignorePatterns } : {}),
    // Settings the hand-rolled per-story configs converged on empirically, now
    // generated defaults: a real DB fixture makes perTest coverage analysis
    // unsound, and parallel runners race on shared database state.
    coverageAnalysis: "off",
    concurrency: 1,
    maxTestRunnerReuse: 1,
    timeoutFactor: 2,
    tempDirName: join(".tmp", `stryker-${digest}`),
  };

  mkdirSync(dirname(GENERATED_CONFIG), { recursive: true });
  writeFileSync(GENERATED_CONFIG, `${JSON.stringify(conf, null, 2)}\n`, "utf8");
  console.log(`mutation-scope: wrote ${GENERATED_CONFIG}`);

  if (process.env.MUTATION_SCOPE_DRY === "1") {
    console.log("mutation-scope: MUTATION_SCOPE_DRY=1 — not running Stryker");
    process.exit(0);
  }

  try {
    execFileSync("pnpm", ["exec", "stryker", "run", GENERATED_CONFIG], { stdio: "inherit" });
  } catch (err) {
    // A non-zero Stryker exit IS the gate failing — propagate the code, but not
    // execFileSync's exception: an uncaught throw prints a JS stack trace after
    // Stryker's own report, which reads as "the tool is broken" rather than
    // "your mutation score is short".
    process.exit(typeof err?.status === "number" ? err.status : 1);
  }
}

main();
// nous-emitted: sha256=84791beeb5bd4bf0
