// drizzle.config.ts — drizzle-kit config (generated by Nous).
// IMP-264 — drizzle-kit auto-loads only `.env`, but `setup.sh` writes
// `.env.local`. Load both (`.env.local` overrides `.env`) so `task setup`
// applies the schema from the env file alone, no manual `export DATABASE_URL`.
import { config } from "dotenv";
import { defineConfig } from "drizzle-kit";

const explicitDatabaseUrl = process.env.DATABASE_URL;
config({ path: ".env" });
config({ path: ".env.local", override: true });
if (explicitDatabaseUrl) process.env.DATABASE_URL = explicitDatabaseUrl;

export default defineConfig({
  schema: "./src/schema.ts",
  out: "./src/migrations",
  dialect: "postgresql",
  dbCredentials: { url: process.env.DATABASE_URL! },
});
