// auth0.ts — Auth0 client config for Mi Banquito (generated by Nous).
// Multi-tenant via Auth0 Organizations: each tenant maps to an org_id.
import { Auth0Client } from "@auth0/nextjs-auth0/server";

export const auth0 = new Auth0Client({
  domain: process.env.AUTH0_DOMAIN,
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  appBaseUrl: process.env.APP_BASE_URL,
  secret: process.env.AUTH0_SECRET,
  authorizationParameters: {
    // Organizations: prompt for org selection at login.
    ...(process.env.AUTH0_ORGANIZATION ? { organization: process.env.AUTH0_ORGANIZATION } : {}),
  },
});
