// auth0.ts — Auth0 client config for Mi Banquito (generated by Nous).
// Multi-tenant via Auth0 Organizations: each tenant maps to an org_id.
import { Auth0Client } from "@auth0/nextjs-auth0/server";
import { parseServerEnv } from "@/lib/env";

const env = parseServerEnv();

export const auth0 = new Auth0Client({
  domain: env.AUTH0_DOMAIN,
  clientId: env.AUTH0_CLIENT_ID,
  clientSecret: env.AUTH0_CLIENT_SECRET,
  appBaseUrl: env.APP_BASE_URL,
  secret: env.AUTH0_SECRET,
  authorizationParameters: {
    // Organizations: prompt for org selection at login.
    ...(env.AUTH0_ORGANIZATION ? { organization: env.AUTH0_ORGANIZATION } : {}),
  },
});
