/**
 * Route constants — auto-generated from Nous navigation map.
 * Use these instead of hardcoding path strings.
 * Regenerate: nous_package.py sync -c agent_files
 */

export const ROUTE_HOME = "/";
export const ROUTE_ACCESS_DENIED = "/acceso-denegado";
export const ROUTE_LOGIN = "/auth/login";
export const ROUTE_SCR_ACCOUNTS = "/cuentas";
export const ROUTE_SCR_ADD_MEMBER = "/socias/nueva";
export const ROUTE_SCR_ADMIN_AUDIT = "/admin/audit";
export const ROUTE_SCR_ADMIN_BUSINESS_RULES = "/admin/orgs/[id]/business-rules";
export const ROUTE_SCR_ADMIN_CRON_RUNS = "/admin/cron-runs";
export const ROUTE_SCR_ADMIN_DRIFT = "/admin/drift";
export const ROUTE_SCR_ADMIN_EXPORT = "/admin/orgs/[id]/export";
export const ROUTE_SCR_ADMIN_HOME = "/admin";
export const ROUTE_SCR_ADMIN_IMPERSONATION = "/admin/orgs/[id]/impersonate";
export const ROUTE_SCR_ADMIN_ORGS_NEW = "/admin/orgs/nueva";
export const ROUTE_SCR_ADMIN_ORG_CONFIG = "/admin/orgs/[id]/config";
export const ROUTE_SCR_ADMIN_ORG_DETAIL = "/admin/orgs/[id]";
export const ROUTE_SCR_ADMIN_PILOT_LOG = "/admin/orgs/[id]/pilot-log";
export const ROUTE_SCR_AR_AGING = "/atrasos";
export const ROUTE_SCR_BALANCE_BANQUITO = "/balance";
export const ROUTE_SCR_CASH_FLOW_PROJECTION = "/liquidez";
export const ROUTE_SCR_CONTRIBUTIONS_CYCLE = "/aportes";
export const ROUTE_SCR_FIRST_RUN_WIZARD = "/bienvenida";
export const ROUTE_SCR_GROUP_CONFIG = "/grupo";
export const ROUTE_SCR_GROUP_PICKER = "/grupos";
export const ROUTE_SCR_HISTORY = "/historial";
export const ROUTE_SCR_LOANS_LIST = "/prestamos";
export const ROUTE_SCR_LOAN_DETAIL = "/prestamos/[id]";
export const ROUTE_SCR_MEMBERS_LIST = "/socias";
export const ROUTE_SCR_MEMBER_DETAIL = "/socias/[id]";
export const ROUTE_SCR_MONTHLY_CLOSE = "/cierre";
export const ROUTE_SCR_ORIGINATE_LOAN = "/prestamos/nuevo";
export const ROUTE_SCR_PUBLIC_VERIFY_PDF = "/verify/[hash]";
export const ROUTE_SCR_RECORD_BASE_FUND_QUOTA = "/cuota-base/registrar";
export const ROUTE_SCR_RECORD_CONTRIBUTION = "/aportes/registrar";
export const ROUTE_SCR_RECORD_MOVEMENT = "/movimientos/registrar";
export const ROUTE_SCR_RECORD_REPAYMENT = "/prestamos/[id]/pago";
export const ROUTE_SCR_SOLIDARITY_COLLECTION = "/colectas";
export const ROUTE_SCR_STATEMENTS_ARCHIVE = "/estados";
export const ROUTE_SCR_TREASURER_HOME = "/";
export const ROUTE_SCR_YEAR_END_SHARE_OUT = "/reparto";

/** All routes as an object for dynamic lookup */
export const ROUTES = {
  HOME: ROUTE_HOME,
  ACCESS_DENIED: ROUTE_ACCESS_DENIED,
  LOGIN: ROUTE_LOGIN,
  SCR_ACCOUNTS: ROUTE_SCR_ACCOUNTS,
  SCR_ADD_MEMBER: ROUTE_SCR_ADD_MEMBER,
  SCR_ADMIN_AUDIT: ROUTE_SCR_ADMIN_AUDIT,
  SCR_ADMIN_BUSINESS_RULES: ROUTE_SCR_ADMIN_BUSINESS_RULES,
  SCR_ADMIN_CRON_RUNS: ROUTE_SCR_ADMIN_CRON_RUNS,
  SCR_ADMIN_DRIFT: ROUTE_SCR_ADMIN_DRIFT,
  SCR_ADMIN_EXPORT: ROUTE_SCR_ADMIN_EXPORT,
  SCR_ADMIN_HOME: ROUTE_SCR_ADMIN_HOME,
  SCR_ADMIN_IMPERSONATION: ROUTE_SCR_ADMIN_IMPERSONATION,
  SCR_ADMIN_ORGS_NEW: ROUTE_SCR_ADMIN_ORGS_NEW,
  SCR_ADMIN_ORG_CONFIG: ROUTE_SCR_ADMIN_ORG_CONFIG,
  SCR_ADMIN_ORG_DETAIL: ROUTE_SCR_ADMIN_ORG_DETAIL,
  SCR_ADMIN_PILOT_LOG: ROUTE_SCR_ADMIN_PILOT_LOG,
  SCR_AR_AGING: ROUTE_SCR_AR_AGING,
  SCR_BALANCE_BANQUITO: ROUTE_SCR_BALANCE_BANQUITO,
  SCR_CASH_FLOW_PROJECTION: ROUTE_SCR_CASH_FLOW_PROJECTION,
  SCR_CONTRIBUTIONS_CYCLE: ROUTE_SCR_CONTRIBUTIONS_CYCLE,
  SCR_FIRST_RUN_WIZARD: ROUTE_SCR_FIRST_RUN_WIZARD,
  SCR_GROUP_CONFIG: ROUTE_SCR_GROUP_CONFIG,
  SCR_GROUP_PICKER: ROUTE_SCR_GROUP_PICKER,
  SCR_HISTORY: ROUTE_SCR_HISTORY,
  SCR_LOANS_LIST: ROUTE_SCR_LOANS_LIST,
  SCR_LOAN_DETAIL: ROUTE_SCR_LOAN_DETAIL,
  SCR_MEMBERS_LIST: ROUTE_SCR_MEMBERS_LIST,
  SCR_MEMBER_DETAIL: ROUTE_SCR_MEMBER_DETAIL,
  SCR_MONTHLY_CLOSE: ROUTE_SCR_MONTHLY_CLOSE,
  SCR_ORIGINATE_LOAN: ROUTE_SCR_ORIGINATE_LOAN,
  SCR_PUBLIC_VERIFY_PDF: ROUTE_SCR_PUBLIC_VERIFY_PDF,
  SCR_RECORD_BASE_FUND_QUOTA: ROUTE_SCR_RECORD_BASE_FUND_QUOTA,
  SCR_RECORD_CONTRIBUTION: ROUTE_SCR_RECORD_CONTRIBUTION,
  SCR_RECORD_MOVEMENT: ROUTE_SCR_RECORD_MOVEMENT,
  SCR_RECORD_REPAYMENT: ROUTE_SCR_RECORD_REPAYMENT,
  SCR_SOLIDARITY_COLLECTION: ROUTE_SCR_SOLIDARITY_COLLECTION,
  SCR_STATEMENTS_ARCHIVE: ROUTE_SCR_STATEMENTS_ARCHIVE,
  SCR_TREASURER_HOME: ROUTE_SCR_TREASURER_HOME,
  SCR_YEAR_END_SHARE_OUT: ROUTE_SCR_YEAR_END_SHARE_OUT,
} as const;
